algorithm: TD3
batch_size: 256
env: Hockey-v0
eval_interval: 5000
gamma: 0.99
implementation: sb3
learning_rate: 0.001
log_dir: logs/TD3/sb3/train
mode: train
policy: MlpPolicy
tensorboard_log: logs/TD3/sb3/train
total_timesteps: 1000000
policy_kwargs: {}
learning_starts: 100