# hp_tuning.yaml
defaults:
  - train
  - _self_

# HP tuning specific parameters
name: hp_tuning
n_trials: 30
n_startup_trials: 5
n_evaluations: 5
study_name: sac_hockey_optimization
n_jobs: 1
storage: sqlite:///logs/${algorithm.name}/sb3/${mode.name}/optuna_studies.db
direction: "maximize"
total_timesteps: 500000
