# config/config.yaml
defaults:
  - _self_
  - algorithm: sac
  - mode: train

# Common parameters
env: Hockey-v1
implementation: sb3
seed: 
- 42
n_eval_envs: 2
parallelize: True
vector_type: subproc # select subproc or dummy
opponent: weak
win_rate_threshold_w_to_s: 0.8
device: "cpu" # "cuda" or "cpu"
change_sides: True

checkpoint:
  load_from: null #logs/SAC/sb3/train/run_2025-02-18_14-45-48_s42 # null # Set to path of checkpoint to load from
  reset_num_timesteps: True  # Whether to reset the timestep counter when loading


hydra:
  run:
    dir: ${get_run_dir:${checkpoint.load_from},${mode.log_dir}}/run_${now:%Y-%m-%d_%H-%M-%S}
