# Prepare moving to Hydra for config management and composition
# config/config.yaml
defaults:
  - _self_
  - algorithm: sac
  - mode: train

# Common parameters
env: Hockey-v1
implementation: sb3
seed: 42
n_eval_envs: 2
parallelize: True
vector_type: subproc # select subproc or dummy
opponent: weak
win_rate_threshold_w_to_s: 0.8

hydra:
  run:
    dir: ${mode.log_dir}/run_${now:%Y-%m-%d_%H-%M-%S}
